---
# defaults file for postgrsql-install
public_signing_key: https://www.postgresql.org/media/keys/ACCC4CF8.asc
postgresql_repo: deb http://apt.postgresql.org/pub/repos/apt jammy-pgdg main
packages: postgresql
